<a href="https://colab.research.google.com/github/jasmineeruizz00/Atividade-ebac/blob/main/Profissao_Cientista_de_Dados_M14_Pratique_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MÓDULO 14 - Exercício**
# Pré Processamento dos Dados - A primeira etapa Pré Modelagem

Para nossa atividade usaremos uma base de churn também, porém essa base não diz respeito a serviços bancários e sim serviços de internet, telefone e tv - Telecomunicação.

Vamos realizar aqui as etapas de limpeza e tratamento de dados vistos durante a aula, porém aplicados a essa base nova.

In [40]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files

arquivo_enviado = files.upload()

Saving CHURN_TELECON_MOD08_TAREFA.csv to CHURN_TELECON_MOD08_TAREFA (2).csv

In [41]:
#Lembrem-se sempre de alterar a importação dos dados de acordo com o diretório de vocês.
df = pd.read_csv("CHURN_TELECON_MOD08_TAREFA.csv", delimiter=';')

df.head(10)

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes
5,9305-CDSKC,NaN,0,No,No,8,Yes,Fiber optic,No,No,Yes,Month-to-month,Electronic check,NaN,820.50,NaN
6,1452-KIOVK,NaN,0,No,Yes,22,Yes,Fiber optic,No,No,Yes,Month-to-month,Credit card (automatic),NaN,1949.40,NaN
7,6713-OKOMC,NaN,0,No,No,10,No,DSL,Yes,No,No,Month-to-month,Mailed check,NaN,301.90,NaN
8,7892-POOKP,NaN,0,Yes,No,28,Yes,Fiber optic,No,Yes,Yes,Month-to-month,Electronic check,NaN,3046.05,NaN
9,6388-TABGU,NaN,0,No,Yes,62,Yes,dsl,Yes,No,No,One year,Bank transfer (automatic),NaN,3487.95,NaN

Legenda dos dados:

*   **CustomerID** : Esse é o ID único de cada cliente nosso da rede de produtos de telecomunicação.

*   **Genero** : O genero dos nossos clientes.

*   **Idoso** : Se nosso cliente tem acima de 60 anos ou não. (Sim = 1 | Não = 0)

*   **Casado** : Se nosso cliente é casado ou não.

*   **Dependents** : Se cliente tem dependentes.

*   **Tempo_como_Cliente** : Tempo em meses que nosso cliente está com a nossa empresa.

*   **PhoneService** : Se ele contratou serviço telefônico com a nossa empresa.

*   **Servico_Internet** : Qual o tipo de serviço de internet contratado.

*   **Servico_Seguranca** : Se ele contratou serviço de segurança com a nossa empresa.

*   **Suporte_Tecnico** : Se já acionou o suporte técnico.

*   **StreamingTV** : Se ele contratou serviço de streaming para TV.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **PaymentMethod** : Forma de Pagamento.

*   **Pagamento_Mensal** : Quanto o cliente pagava mensalmente.

*   **Total_Pago** : Total já pago pelo cliente para nossa companhia.

*   **Churn** : Nossa coluna mais importante, se nosso cliente nos abandonou ou não.

# 1 - Carregue a base, verifique se os tipos de dados estão de acordo com cada coluna e caso não estejam realize a transformação dos tipos de dados.

In [42]:
df.dtypes

customerID             object
Genero                 object
Idoso                   int64
Casado                 object
Dependents             object
Tempo_como_Cliente      int64
PhoneService           object
Servico_Internet       object
Servico_Seguranca      object
Suporte_Tecnico        object
StreamingTV            object
Tipo_Contrato          object
PaymentMethod          object
Pagamento_Mensal      float64
Total_Pago            float64
Churn                  object
dtype: object

# 2 - Esse exercício faremos por etapas:
A) Verifique se temos colunas com dados faltantes e traga a % dos dados faltantes por coluna.

In [43]:
(df.isnull().sum() / len(df)) *100

customerID             0.00
Genero                 0.48
Idoso                  0.00
Casado                 0.00
Dependents             0.00
Tempo_como_Cliente     0.00
PhoneService          59.28
Servico_Internet       0.00
Servico_Seguranca      0.00
Suporte_Tecnico        0.00
StreamingTV            0.00
Tipo_Contrato          0.00
PaymentMethod          0.00
Pagamento_Mensal      13.00
Total_Pago             0.00
Churn                  0.20
dtype: float64

B) Exclua nessa etapa as linhas das colunas com dados faltantes que você analisar que esse método é o ideal. Justifique o motivo de estar excluindo essas linhas.

Como a coluna Genero possui uma porcentagem muito baixa de dados nulos (0,48%), optei por excluir as linhas com valores ausentes nessa coluna. Essa remoção terá impacto mínimo na base de dados e evita preencher os valores com uma informação que não pode ser inferida com segurança.

In [44]:
df.dropna(subset=['Genero'], inplace=True)

C) Nessa etapa substitua pela média, mediana ou moda as linhas das colunas com valores faltantes que você analisou e entendeu que esse era o melhor método. Não se esqueça de justificar sua escolha.

**Dica variáveis numéricas:** Não se esqueça de verificar a distrbuição dos dados, média e mediana.

**Dica variáveis categóricas:** Caso precise substituir uma variável categórica utilize um gráfico de barras para verificar a que mais aparece e utilizar ela na substituição.
Ou você pode optar por excluir a coluna, mas justifique sua escolha.

Caso opte por substituir você pode utilizar a função fillna:
df['SUACOLUNA'].fillna("VALOR QUE SUBSTITUIRA O NULO", inplace=True)
Ela funcionará como a replace.

In [45]:
df["Pagamento_Mensal"] = df["Pagamento_Mensal"].fillna( df["Total_Pago"] / df["Tempo_como_Cliente"].replace(0, pd.NA))

/tmp/ipykernel_1012/3572900965.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Pagamento_Mensal"] = df["Pagamento_Mensal"].fillna( df["Total_Pago"] / df["Tempo_como_Cliente"].replace(0, pd.NA))

A coluna Pagamento_Mensal possui valores nulos e foi preenchida utilizando a relação entre Total_Pago e Tempo_como_Cliente, pois essa fórmula permite estimar o valor mensal pago por cada cliente de forma coerente com a estrutura dos dados. Essa abordagem mantém a consistência da base e evita a perda de registros.

In [46]:
df['PhoneService'] = df['PhoneService'].fillna('Sem informacao')

A coluna Servico_Telefonico possui uma alta quantidade de valores nulos. Em vez de excluir a coluna, optei por substituir os valores ausentes por Sem informacao, preservando os registros e evitando perda de dados.

# 3 - Verifique se encontramos valores digitados incorretamente, ou com letras maiusculas ou minusculas, ou até mesmo mesmos valores porém escritos de forma dirente e corrija.

In [47]:
for col in df.select_dtypes(include='object').columns:
    print(f"\nColuna: {col}")
    print(df[col].value_counts(dropna=False))

Coluna: customerID
customerID
6061-GWWAV    1
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
             ..
6322-HRPFA    1
3638-WEABW    1
1066-JKSGK    1
1680-VDCWW    1
8779-QRDMV    1
Name: count, Length: 2488, dtype: int64

Coluna: Genero
Genero
Male      1265
Female    1212
M            4
f            4
F            3
Name: count, dtype: int64

Coluna: Casado
Casado
No     1262
Yes    1226
Name: count, dtype: int64

Coluna: Dependents
Dependents
No     1705
Yes     783
Name: count, dtype: int64

Coluna: PhoneService
PhoneService
Sem informacao    1482
Yes                920
No                  86
Name: count, dtype: int64

Coluna: Servico_Internet
Servico_Internet
Fiber optic    1119
DSL             835
No              527
dsl               7
Name: count, dtype: int64

Coluna: Servico_Seguranca
Servico_Seguranca
No                     1254
Yes                     707
No internet service     527
Name: count, dtype: int64

Coluna: Suporte_Tecnico
Suporte_Tecnico
No                     1250
Yes                     711
No internet service     527
Name: count, dtype: int64

Coluna: StreamingTV
StreamingTV
No                     1001
Yes                     960
No internet service     527
Name: count, dtype: int64

Coluna: Tipo_Contrato
Tipo_Contrato
Month-to-month    1369
Two year           602
One year           517
Name: count, dtype: int64

Coluna: PaymentMethod
PaymentMethod
Electronic check             830
Bank transfer (automatic)    579
Credit card (automatic)      551
Mailed check                 528
Name: count, dtype: int64

Coluna: Churn
Churn
No     1841
Yes     647
Name: count, dtype: int64

In [48]:
df['Genero'] = df['Genero'].replace({ 'M': 'Male', 'F': 'Female', 'f': 'Female'})
df['Servico_Internet'] = df['Servico_Internet'].replace({'dsl': 'DSL'})
print(df['Genero'].value_counts(dropna=False))
print(df['Servico_Internet'].value_counts(dropna=False))

Genero
Male      1269
Female    1219
Name: count, dtype: int64
Servico_Internet
Fiber optic    1119
DSL             842
No              527
Name: count, dtype: int64

# [EXTRA] 4 - Caso deseje, para manter um padrão na sua base, renomeie as colunas ou deixando em português, ou inglês.

In [49]:
df.rename(columns={"PhoneService": "Servico_Telefonico","PaymentMethod": "Forma_Pagamento","Dependents": "Dependentes"
}, inplace=True)